
export const CLEAR_RANDOM_PLAYLIST = 'CLEAR_RANDOM_PLAYLIST'
export const DECREMENT_RANDOM_PLAYLIST_ID = 'DECREMENT_RANDOM_PLAYLIST_ID'
export const INCREMENT_RANDOM_PLAYLIST_ID = 'INCREMENT_RANDOM_PLAYLIST_ID'
export const DECREMENT_CURRENT_TRACK_ID = 'DECREMENT_CURRENT_TRACK_ID'
export const INCREMENT_CURRENT_TRACK_ID = 'INCREMENT_CURRENT_TRACK_ID'
export const SET_VOLUME = 'SET_VOLUME'
export const SET_MODE = 'SET_MODE'
export const SET_PROGRESS = 'SET_PROGRESS'
export const SET_IS_PAUSED = 'SET_IS_PAUSED'
export const SET_CURRENT_TRACK_ID = 'SET_CURRENT_TRACK_ID'
export const SET_CURRENT_TRACK_NAME = 'SET_CURRENT_TRACK_NAME'
export const SET_PLAYLIST = 'SET_PLAYLIST'
export const SET_RANDOM_PLAYLIST = 'SET_RANDOM_PLAYLIST'
export const SET_RANDOM_PLAYLIST_ID = 'SET_RANDOM_PLAYLIST_ID'

export const FETCH_TRACK = 'FETCH_TRACK'
export const FETCH_TRACK_LOADING = 'FETCH_TRACK_LOADING'
export const FETCH_TRACK_SUCCESS = 'FETCH_TRACK_SUCCESS'
export const FETCH_TRACK_ERROR = 'FETCH_TRACK_ERROR'


export const MODE = {
    PLAY_ALL: 'PLAY_ALL',
    SHUFFLE: 'SHUFFLE',
    LOOP: 'LOOP'
}